### ISSUE TITLE
SHARDS_AND_DAYS hint will fail to parse without parens

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1030]
For a query like (FOO == 'bar' && SHARDS_AND_DAYS = '20200101_1'), the shards and days hit will be trimmed.  It appears that the shards and days hint is required to be inside it's own parens to work.  Unless this is a JEXL language issue, parens should not be required.

**Comment by jwomeara** [comment]
Looked into this a little bit this morning.  For a query like:
```
FOO == 'bar' && SHARDS_AND_DAYS = '20200101_1'
```
the jexl parser reads that as
```
((FOO == 'bar' && SHARDS_AND_DAYS) = '20200101_1')
```

So, what's happening is that it's treating the entire query like it's a mathematical expression where the result equals '20200101_1'

So, we have a few options:
1) before the query is parsed use a regex to match SHARDS_AND_DAYS assignments and surround them with parens
2) simply accept that SHARDS_AND_DAYS needs to be surrounded in parens in order to work correctly
3) make SHARDS_AND_DAYS a function instead
4) make a visitor that runs after the query is parsed that matches up the SHARD_AND_DAYS field with it's value

In my opinion, option number 3 is the simplest, most straightforward way to fix this.  Options 1 and 4 are probably going to be nontrivial to implement.

**Comment by jwomeara** [comment]
I thought of another option which I like even better.  Let's update our options function to accept SHARDS_AND_DAYS and have users set it there.  That way we're converging towards a common method for setting options which apply to the whole query.

**Comment by ivakegg** [comment]
Interesting.  So this is actually working as the Jexl parser is designed to work.  If that is the case then I am OK with option 2 (leave this working as desinged).  However I have no objections to providing a function or extending the OPTIONS function.

**Comment by ivakegg** [comment]
Also we should make sure that the flattening visitor does not remove reference expressions around assignments.

**Comment by lbschanno** [comment]
@ivakegg after some testing it looks like the flattening visitor does not remove reference expressions around assignments. I checked the code within the TreeFlatteningRebuilder to confirm that the references are intentionally preserved.
