### ISSUE TITLE
EventDataQueryExpressionVisitor should test normalized field values against normalized patterns

### ISSUE THREAD

**Issue by FineAndDandy** [NationalSecurityAgency/datawave#224]
EventDataQueryExpressionVisitor.apply() is using the normalized field values to accept/reject Keys, as a result the fieldValues, fieldRanges, and fieldPatterns must be normalized as well otherwise matches may be missed

**Comment by drewfarris** [comment]
After some discussion @FineAndDandy and I realize this should not only do the normalized case, but also handle the non-normalized case (so that potentially both versions are included in the context that gets sent to Jexl for evalation). This will handle the case where we have a regular expression that would match the non-normalized version of the field value, yet does not match the normalized form. Currently, if we encounter that case - we fail to properly include the value in the context for evaluation, possibly ignoring a field value that would otherwise match the expression.
