### ISSUE TITLE
Running Authentication & Authorization services/authorization micro-service via IDE

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#329]
Keith,

Again, thanks for the help thus far.

**Here is the scenario I have (what I am trying to accomplish in stage 1 ofd what I am working on:**
I would like to trace through Authorization Service and get an understanding of how it works so I can work on a task that involves Authentication and Authorization.  NOTE: I am new to DW.

**So far, I have done the following:**

1. I have loaded datawave into my ItelliJ.  I am following the instructions in datawave-master/services/README.md. 

2. I copied the `.example` files in the `sample_configuration` directory to the same name without `.example`(e.g., `authorization-dev.yml.example` becomes `authorization-dev.yml`).   I have not yet edited any of the files I copied to apply any customization.  I wanted to just run it as is without adding another variable.

**My question:**
1.    Now that I have DW running, using the artifacts you had provided, if I build the DATAWAVE microservices as follow (instructions in the README.md file mentioned above):

cd /path/to/datawave/services/build-parent
mvn -Pexec clean install
# You can add -DskipTests to skip running unit tests
# You can add -Pdocker to build Docker images

Will this or the instructions the follow this first step affect the running service?

2.   If I am making this to complicated and the is a better way to accomplish what I am trying to accomplish in this phase, please do recommend.

Thank you
Rich :)

**Comment by keith-ratcliffe** [comment]
> Will this or the instructions the follow this first step affect the running service?

It is unclear which running service is being referenced here

> If I am making this to complicated and the is a better way to accomplish what I am trying to accomplish in this phase, please do recommend.

It is unclear what is at issue here and unclear what is being attempted.

Sorry, closing this issue because it **1)** doesn't relate to a possible bug/defect with the software and **2)** doesn't relate to a proposed software enhancement

This seems to be a request for general assistance related to how the software might behave under certain hypothetical situations, which are unclear. We can't really support these kinds of requests here. Typically, we only accept issues that fall into one of the two categories referenced above
