### ISSUE TITLE
Populate normalization column in the data dictionay

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#479]
Currently the normalization column is not being filled in on the data dictionary web page.  This should describe whether the field is normalized in the event ('n' cf in the DatawaveMetadata table).

**Comment by jschmidt10** [comment]
I think we now use 't' column families that represent Type. The Type implementation will handle normalizing, usually via an underlying Normalizer.

**Comment by jzgithub1** [comment]
There are 't' column family entries in the datawave.metadata table in the Quickstart and I will have to add it to the documentation.  In this document: https://code.nsa.gov/datawave/docs/2.6/getting-started/data-model there is neither an 'n' or a 't' column family.   There is a 'tf' which does this: The tf column family denotes that NFN within type DT has term frequency CF entries, which enables phrase queries, etc.  

The only fields related to normalization in the doc page are:
'i'    -    The i column family denotes that NFN is in the Global Forward Index table and that it is normalized using NCN, for the given DT 
and
'ri'   -   The ri column family denotes that NFN is in the Global Reverse Index table and that it is normalized using NCN, for the given DT 

@jschmidt10, thank you for your comment because it gave me a clue about how to do what @ivakegg  wants.

This is how it is computed now: 
`builder.append("<td>").append(f.isNormalized() ? true : "").append("</td>");`  Its always empty string.

Maybe we want to compute the Normalize column value like this?: 
` builder.append("<td>").append(f.getTypes().size() > 0 ? true : "").append("</td>");`

I have scanned the datawave.metadata table in the Quickstart install and looked at actual data and see a lot of NFN's with the 't' column family.
