### ISSUE TITLE
Getting the source node of a marked node should not reparent those nodes

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#603]
Discovered a bug where getting the source node for a marked node was actually reparenting those child nodes to an orphaned, and node.  So, while the original parent still has knowledge of his children, the children think they have a new parent.

**Comment by apmoriarty** [comment]
The index lookup code does not reparent jexl nodes. Specific class to look at include
- IndexMatch
- IndexInfo
- Intersection
- Union

**Comment by jwomeara** [comment]
My advice would be to either update our logic to accept a list of source nodes, or update our tree logic to ensure that multiple source nodes are always parented by an and node.

**Comment by ivakegg** [comment]
Preference is to return a list of source nodes instead of a single node.

**Comment by lbschanno** [comment]
This particular bug occurs due to this [line](https://github.com/NationalSecurityAgency/datawave/blob/76369d76ff76d58d37833df5224cf3ea8f932826/warehouse/query-core/src/main/java/datawave/query/jexl/nodes/QueryPropertyMarker.java#L102), and only occurs when there are multiple source nodes that are not wrapped, e.g.

`(_Term_ = true) && FOO == 'a' && BAR == 'b')` will result in the source nodes being re-parented by a new AND node, but 
`(_Term_ = true) && (FOO == 'a' && BAR == 'b'))` will not.

While the preference is to return a list of source nodes instead of a single node, this will result in the need for extensive refactoring in a number of places that are dependent on processing a singular node. A simpler approach would be to ensure that source nodes are always wrapped in the first place. 

An even more simple approach would be to return a new AND node that has the source nodes as children, but is NOT their parent. However, that opens up the possibility for bugs down the road where it may be assumed that the AND node has a valid structure.

My vote is to ensure source nodes are wrapped so that there is only one root source node.

**Comment by ivakegg** [comment]
I think ensuring single source node is reasonable.  Lets create a visitor that will wrap the source nodes appropriately with a reference and reference expression when needed.  This is required in case a user attempts to add a marker node in manually as the initial query.  Then we can add a visitor to ensure that this rule is not violated as we did with the parentage checking visitor.  I expect we will need to fix a few places that create these marker nodes and would violate this rule.  Also I think @apmoriarty has a pull request that allows us to call a set of tree verification visitors through out the default query planner.
