### ISSUE TITLE
quick start test fails

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#794]
in release/version2.8 (not sure when this got broken) when testing the quickstart (datawaveWebTest):
```
Test UID: EventQuery400BadRequest/IntentionalError
Test Description: Creates an error for EventQuery by omitting all required query params

HTTP Response Status Code: 500
HTTP Response ContentType: application/xml;charset=UTF-8

Test Total Time: 0.058184
Test Status: 
[X] FAILED - Expected Code: '400' Actual: '500'
```
The stack trace in server.log:
```
Caused by: java.lang.NullPointerException: Query string cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:209)
        at datawave.webservice.query.QueryParametersImpl.validate(QueryParametersImpl.java:98)
        at datawave.webservice.query.runner.QueryExecutorBean.validateQuery(QueryExecutorBean.java:42)
        at datawave.webservice.query.runner.QueryExecutorBean.createQuery(QueryExecutorBean.java:623)
```

**Comment by keith-ratcliffe** [comment]
Can't replicate on release/version2.8. Thinking that a prior quickstart build got deployed for you in this case.

In release/version2.8, server.log should have this for the stacktrace instead:
```
Caused by: java.lang.NullPointerException: QueryParameter 'query' cannot be null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:209)
at datawave.webservice.query.QueryParametersImpl.validate(QueryParametersImpl.java:125)
```
Message text (and apparently the status code) got changed a while back
```
git log -p --follow -- \
web-services/client/src/main/java/datawave/webservice/query/QueryParametersImpl.java \
| grep -E "^commit|Query string cannot be null"

commit 30c9cef846f07624fd0cae648fc453501ee8f403
commit 055b21f0d0a2097b8f749797f162f3a2489dcfb1
commit b9a1c8bc4177641078d0a709808f11484d07dc83
-        Preconditions.checkNotNull(this.query, "Query string cannot be null");
commit 7f51e2668227f0a8ece3ae12d96ebfac43eafacf
commit 6c2d4310579f9ee5434640b4ff65c78656a3e2c0
commit 37148c47d004b05be27670799b67c4db53230410
commit 2f028f3f3f69e423506c1b8873183fdecac09f5e
+        Preconditions.checkNotNull(this.query, "Query string cannot be null");
```
The quickstart **allInstall** operation will prefer your previously-downloaded / -built tarballs, rather than forcing a re-download of dependencies and rebuild of DW. Likewise, **allUninstall** by default will retain all your tarballs to save time on reinstall attempts. You can override that with **allUninstall --remove-binaries** to completely start over from scratch

Admittedly, the quickstart could do a better job here. I think both allInstall and allIUinstall should be improved, so that the user gets advanced notice on exactly which tarballs are about to be operated on. We could do that under this ticket, or create a new one
