### ISSUE TITLE
Exceptions thrown when evaluating functions are silently swallowed

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#887]
DatawaveInterpreter uses strict=false during evaluation which results in no error being thrown if an exception is encountered during a method invocation (any function).  There are multiple places in the interpreter code which test strict before throwing exceptions.  Specifically the invocationFailed() is responsible for deciding to throw exceptions from inside called functions.  This may result in missed hits.

If a function in the query throws an exception, it should error the query.  Note that setting strict=false may be required for other reasons (to be verified).

**Comment by ivakegg** [comment]
We found a few functions that cannot handle a null field value.  e.g. EvaluationPhaseFilterFunctions.betweenDates(Object fieldValue, ..._)

**Comment by ivakegg** [comment]
I fixed that one function, but I would like @lbschanno to check all of the other functions to ensure we are handling null field values correctly.

**Comment by billoley** [comment]
I am creating a PR for adding additional null checks since we are trying to use the release/version3.2 branch and having unnecessary exceptions being thrown due to data variability is not a great idea

**Comment by billoley** [comment]
The goal here is to make it so that the InvocationException that is no longer being swallowed does not prevent valid queries from running for the sole reason that a field (referenced in the queryTree) does not have a value and thus a null is passed to a function.  If the query itself has bad parameters that are not field value based, then the exception should bring down the query.

**Comment by codebyneesh** [comment]
I will take over adding additional null checks.
